CREATE DATABASE IF NOT EXISTS armchairgm;
USE armchairgm;

CREATE TABLE Players (
  PlayerID INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(100),
  Position VARCHAR(20),
  Team VARCHAR(50),
  WAR FLOAT,
  OPS FLOAT,
  ERA FLOAT,
  Salary DECIMAL(10,2),
  Age INT
);
